### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by Kelechikizito**
This pull request was created by https://app.gib.work/i/Wz6QMzyl/document-the-new-tipping-feature in an attempt to solve a bounty. Payment for the bounty is immediately sent to the contributor after merge.

### CODE REVIEW

**Comment by anthonyliriano** [comment]
@gibworkbot tip 5 @Kelechikizito

**Comment by anthonyliriano** [comment]
@gibwork bot tip 5 @Kelechikizito

**Comment by anthonyliriano** [comment]
@gibworkbot tip 5 @Kelechikizito

**Comment by Kelechikizito** [comment]
@anthonyliriano Thank you, I've claimed the tip. Looking forward to help contribute in the future.

**Pull request closed without merging**
